Homework_2 Numpy

In [2]:
import numpy as np

1 Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [3]:
x = np.zeros((10, 10))
x[0, :] = 1
x[-1, :] = 1
x[:, 0] = 1
x[:, -1] = 1
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2 Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [4]:
x = np.zeros((8, 8))
x[::2, ::2] = 1
x[1::2, 1::2] = 1
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


3 Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [5]:
y = np.diag((1, 2, 3, 4))
y = np.vstack(([0, 0, 0, 0], y))
print(np.hstack((y, np.zeros((5, 1)))))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


4 Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [14]:
x = np.random.random((5, 5))
print("old_mean",x.mean(axis=1))
xmean = x.mean(axis=1).reshape(5, 1)
x = x - xmean
print("new_mean", x.mean(axis=1))

old_mean [0.60964727 0.52115711 0.58542251 0.60954115 0.51936293]
new_mean [ 2.22044605e-17  0.00000000e+00  0.00000000e+00  2.22044605e-17
 -6.66133815e-17]


5 Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [13]:
x = np.random.random((10, 3))
print(x)
y = (np.abs(x-0.5)).argmin(axis=1)
print(x[np.arange(10), y])

[[0.34886928 0.47388855 0.56795634]
 [0.0706969  0.11641879 0.89798852]
 [0.62103985 0.78772431 0.37100027]
 [0.11160182 0.06775107 0.83015781]
 [0.2750702  0.9969607  0.53051457]
 [0.88656757 0.31713986 0.51243632]
 [0.24105854 0.7658034  0.94358823]
 [0.19204604 0.55406486 0.11692174]
 [0.71473857 0.54186696 0.74461136]
 [0.53539126 0.6763002  0.93111999]]
[0.47388855 0.11641879 0.62103985 0.83015781 0.53051457 0.51243632
 0.24105854 0.55406486 0.54186696 0.53539126]


6 Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [11]:
x = np.random.random((6, 6))
#print(x)
str_sum = x.sum(axis=1)
col_max = x.max(axis=0)
print(str_sum / col_max)

[2.73089589 3.16836176 6.01564109 3.06797799 3.33525014 2.74954004]


7 На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [9]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(np.max(x[np.where(x == 0)[0][:-1] + 1]))

5


8 Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [10]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
np.add.at(x, i, 1)
print(x)


[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
